version: "3.0"
services:
  crablog:
    build: .
    image: mtrx1337/crablog
    ports:
        - 8000:8000
    hostname: crablog
    container_name: crablog
    env_file: ./crablog.env
    restart: unless-stopped
    volumes:
      - ./content:/app/content
